chibios_rt::ThreadReference Class Reference
chibios_rt::ThreadReference Class Reference
Various » C++ Wrapper
Detailed Description
Thread reference class.
This class encapsulates a reference to a system thread. All operations involving another thread are performed through an object of this type.
Definition at line 234 of file ch.hpp.
#include <ch.hpp>
Public Member Functions
ThreadReference (Thread *tp)
Thread reference constructor.
virtual void stop (void)
Stops the thread.
msg_t suspend (void)
Suspends the current thread on the reference.
msg_t suspendS (void)
Suspends the current thread on the reference.
void resume (msg_t msg)
Resumes the currently referenced thread, if any.
void resumeI (msg_t msg)
Resumes the currently referenced thread, if any.
void requestTerminate (void)
Requests a thread termination.
msg_t wait (void)
Blocks the execution of the invoking thread until the specified thread terminates then the exit code is returned.
msg_t sendMessage (msg_t msg)
Sends a message to the thread and returns the answer.
bool isPendingMessage (void)
Returns true if there is at least one message in queue.
msg_t getMessage (void)
Returns an enqueued message or NULL.
void releaseMessage (msg_t msg)
Releases the next message in queue with a reply.
void signalEvents (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
void signalEventsI (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
Data Fields
::Thread * thread_ref
Pointer to the system thread.
Constructor & Destructor Documentation
chibios_rt::ThreadReference::ThreadReference (Thread * tp) inline
Thread reference constructor.
Parameters
[in] tp the target thread. This parameter can be NULL if the thread is not known at creation time.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 250 of file ch.hpp.
Member Function Documentation
void chibios_rt::ThreadReference::stop (void) virtual
Stops the thread.
Note
The implementation is left to descendant classes and is optional.
Definition at line 107 of file ch.cpp.
References chDbgPanic().
msg_t chibios_rt::ThreadReference::suspend (void)
Suspends the current thread on the reference.
The suspended thread becomes the referenced thread. It is possible to use this method only if the thread reference was set to NULL.
Returns
The incoming message.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 112 of file ch.cpp.
References chDbgAssert, chSchGoSleepS(), chSysLock, chSysUnlock, chThdSelf, Thread::p_u, Thread::rdymsg, THD_STATE_SUSPENDED, and thread_ref.
msg_t chibios_rt::ThreadReference::suspendS (void)
Suspends the current thread on the reference.
The suspended thread becomes the referenced thread. It is possible to use this method only if the thread reference was set to NULL.
Returns
The incoming message.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 129 of file ch.cpp.
References chDbgAssert, chSchGoSleepS(), chThdSelf, Thread::p_u, Thread::rdymsg, THD_STATE_SUSPENDED, and thread_ref.
void chibios_rt::ThreadReference::resume (msg_t msg)
Resumes the currently referenced thread, if any.
Parameters
[in] msg the wakeup message
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 140 of file ch.cpp.
References chDbgAssert, chSchWakeupS(), chSysLock, chSysUnlock, and thread_ref.
void chibios_rt::ThreadReference::resumeI (msg_t msg)
Resumes the currently referenced thread, if any.
Parameters
[in] msg the wakeup message
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 157 of file ch.cpp.
References chDbgAssert, chSchReadyI(), Thread::p_msg, and thread_ref.
void chibios_rt::ThreadReference::requestTerminate (void)
Requests a thread termination.
Precondition
The target thread must be written to invoke periodically chThdShouldTerminate() and terminate cleanly if it returns TRUE.
Postcondition
The specified thread will terminate after detecting the termination condition.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 171 of file ch.cpp.
References chDbgAssert, chThdTerminate(), and thread_ref.
msg_t chibios_rt::ThreadReference::wait (void)
Blocks the execution of the invoking thread until the specified thread terminates then the exit code is returned.
This function waits for the specified thread to terminate then decrements its reference counter, if the counter reaches zero then the thread working area is returned to the proper allocator.
The memory used by the exited thread is handled in different ways depending on the API that spawned the thread:
If the thread was spawned by chThdCreateStatic() or by chThdCreateI() then nothing happens and the thread working area is not released or modified in any way. This is the default, totally static, behavior.
If the thread was spawned by chThdCreateFromHeap() then the working area is returned to the system heap.
If the thread was spawned by chThdCreateFromMemoryPool() then the working area is returned to the owning memory pool.
Precondition
The configuration option CH_USE_WAITEXIT must be enabled in order to use this function.
Postcondition
Enabling chThdWait() requires 2-4 (depending on the architecture) extra bytes in the Thread structure.
After invoking chThdWait() the thread pointer becomes invalid and must not be used as parameter for further system calls.
Note
If CH_USE_DYNAMIC is not specified this function just waits for the thread termination, no memory allocators are involved.
Returns
The exit code from the terminated thread.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
msg_t chibios_rt::ThreadReference::sendMessage (msg_t msg)
Sends a message to the thread and returns the answer.
Parameters
[in] msg the sent message
Returns
The returned message.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
bool chibios_rt::ThreadReference::isPendingMessage (void)
Returns true if there is at least one message in queue.
Return values
true A message is waiting in queue.
false A message is not waiting in queue.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
msg_t chibios_rt::ThreadReference::getMessage (void)
Returns an enqueued message or NULL.
Returns
The incoming message.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void chibios_rt::ThreadReference::releaseMessage (msg_t msg)
Releases the next message in queue with a reply.
Parameters
[in] msg the answer message
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void chibios_rt::ThreadReference::signalEvents (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
Parameters
[in] mask the event flags set to be ORed
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
void chibios_rt::ThreadReference::signalEventsI (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
Parameters
[in] mask the event flags set to be ORed
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Field Documentation
::Thread* chibios_rt::ThreadReference::thread_ref
Pointer to the system thread.
Definition at line 239 of file ch.hpp.
Referenced by requestTerminate(), resume(), resumeI(), chibios_rt::BaseStaticThread< N >::start(), suspend(), and suspendS().