chibios_rt::Core Class Reference
chibios_rt::Core Class Reference
Various » C++ Wrapper
Detailed Description
Class encapsulating the base system functionalities.
Definition at line 133 of file ch.hpp.
#include <ch.hpp>
Static Public Member Functions
static void * alloc (size_t size)
Allocates a memory block.
static void * allocI (size_t size)
Allocates a memory block.
static size_t getStatus (void)
Core memory status.
Member Function Documentation
void * chibios_rt::Core::alloc (size_t size) static
Allocates a memory block.
The size of the returned block is aligned to the alignment type so it is not possible to allocate less than MEM_ALIGN_SIZE.
Parameters
[in] size the size of the block to be allocated
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 69 of file ch.cpp.
References chCoreAlloc().
void * chibios_rt::Core::allocI (size_t size) static
Allocates a memory block.
The size of the returned block is aligned to the alignment type so it is not possible to allocate less than MEM_ALIGN_SIZE.
Parameters
[in] size the size of the block to be allocated.
Returns
A pointer to the allocated memory block.
Return values
NULL allocation failed, core memory exhausted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 74 of file ch.cpp.
References chCoreAllocI().
size_t chibios_rt::Core::getStatus (void) static
Core memory status.
Returns
The size, in bytes, of the free core memory.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 79 of file ch.cpp.
References chCoreStatus().