chibios_rt::BaseThread Class Reference
chibios_rt::BaseThread Class Reference
Various » C++ Wrapper
Detailed Description
Abstract base class for a ChibiOS/RT thread.
The thread body is the virtual function Main().
Definition at line 422 of file ch.hpp.
#include <ch.hpp>
Public Member Functions
BaseThread (void)
BaseThread constructor.
virtual msg_t main (void)
Thread body function.
virtual ThreadReference start (tprio_t prio)
Creates and starts a system thread.
Public Member Functions inherited from chibios_rt::ThreadReference
ThreadReference (Thread *tp)
Thread reference constructor.
virtual void stop (void)
Stops the thread.
msg_t suspend (void)
Suspends the current thread on the reference.
msg_t suspendS (void)
Suspends the current thread on the reference.
void resume (msg_t msg)
Resumes the currently referenced thread, if any.
void resumeI (msg_t msg)
Resumes the currently referenced thread, if any.
void requestTerminate (void)
Requests a thread termination.
msg_t wait (void)
Blocks the execution of the invoking thread until the specified thread terminates then the exit code is returned.
msg_t sendMessage (msg_t msg)
Sends a message to the thread and returns the answer.
bool isPendingMessage (void)
Returns true if there is at least one message in queue.
msg_t getMessage (void)
Returns an enqueued message or NULL.
void releaseMessage (msg_t msg)
Releases the next message in queue with a reply.
void signalEvents (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
void signalEventsI (eventmask_t mask)
Adds a set of event flags directly to specified Thread.
Static Public Member Functions
static void setName (const char *tname)
Sets the current thread name.
static tprio_t setPriority (tprio_t newprio)
Changes the running thread priority level then reschedules if necessary.
static void exit (msg_t msg)
Terminates the current thread.
static void exitS (msg_t msg)
Terminates the current thread.
static bool shouldTerminate (void)
Verifies if the current thread has a termination request pending.
static void sleep (systime_t interval)
Suspends the invoking thread for the specified time.
static void sleepUntil (systime_t time)
Suspends the invoking thread until the system time arrives to the specified value.
static void yield (void)
Yields the time slot.
static ThreadReference waitMessage (void)
Waits for a message.
static eventmask_t getAndClearEvents (eventmask_t mask)
Clears the pending events specified in the mask.
static eventmask_t addEvents (eventmask_t mask)
Adds (OR) a set of event flags on the current thread, this is much faster than using chEvtBroadcast() or chEvtSignal().
static eventmask_t waitOneEvent (eventmask_t ewmask)
Waits for a single event.
static eventmask_t waitAnyEvent (eventmask_t ewmask)
Waits for any of the specified events.
static eventmask_t waitAllEvents (eventmask_t ewmask)
Waits for all the specified event flags then clears them.
static eventmask_t waitOneEventTimeout (eventmask_t ewmask, systime_t time)
Waits for a single event.
static eventmask_t waitAnyEventTimeout (eventmask_t ewmask, systime_t time)
Waits for any of the specified events.
static eventmask_t waitAllEventsTimeout (eventmask_t ewmask, systime_t time)
Waits for all the specified event flags then clears them.
static void dispatchEvents (const evhandler_t handlers[], eventmask_t mask)
Invokes the event handlers associated to an event flags mask.
static void unlockMutex (void)
Unlocks the next owned mutex in reverse lock order.
static void unlockMutexS (void)
Unlocks the next owned mutex in reverse lock order.
static void unlockAllMutexes (void)
Unlocks all the mutexes owned by the invoking thread.
Additional Inherited Members
Data Fields inherited from chibios_rt::ThreadReference
::Thread * thread_ref
Pointer to the system thread.
Constructor & Destructor Documentation
chibios_rt::BaseThread::BaseThread (void)
BaseThread constructor.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 257 of file ch.cpp.
Member Function Documentation
msg_t chibios_rt::BaseThread::main (void) virtual
Thread body function.
Returns
The exit message.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 261 of file ch.cpp.
ThreadReference chibios_rt::BaseThread::start (tprio_t prio) virtual
Creates and starts a system thread.
Parameters
[in] prio thread priority
Returns
A reference to the created thread with reference counter set to one.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Reimplemented in chibios_rt::BaseStaticThread< N >.
Definition at line 266 of file ch.cpp.
void chibios_rt::BaseThread::setName (const char * tname) static
Sets the current thread name.
Precondition
This function only stores the pointer to the name if the option CH_USE_REGISTRY is enabled else no action is performed.
Parameters
[in] tname thread name as a zero terminated string
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 278 of file ch.cpp.
References chRegSetThreadName.
tprio_t chibios_rt::BaseThread::setPriority (tprio_t newprio) static
Changes the running thread priority level then reschedules if necessary.
Note
The function returns the real thread priority regardless of the current priority that could be higher than the real priority because the priority inheritance mechanism.
Parameters
[in] newprio the new priority level of the running thread
Returns
The old priority level.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 283 of file ch.cpp.
References chThdSetPriority().
void chibios_rt::BaseThread::exit (msg_t msg) static
Terminates the current thread.
The thread goes in the THD_STATE_FINAL state holding the specified exit status code, other threads can retrieve the exit status code by invoking the function chThdWait().
Postcondition
Eventual code after this function will never be executed, this function never returns. The compiler has no way to know this so do not assume that the compiler would remove the dead code.
Parameters
[in] msg thread exit code
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 288 of file ch.cpp.
References chThdExit().
void chibios_rt::BaseThread::exitS (msg_t msg) static
Terminates the current thread.
The thread goes in the THD_STATE_FINAL state holding the specified exit status code, other threads can retrieve the exit status code by invoking the function chThdWait().
Postcondition
Eventual code after this function will never be executed, this function never returns. The compiler has no way to know this so do not assume that the compiler would remove the dead code.
Parameters
[in] msg thread exit code
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 293 of file ch.cpp.
References chThdExitS().
bool chibios_rt::BaseThread::shouldTerminate (void) static
Verifies if the current thread has a termination request pending.
Note
Can be invoked in any context.
Return values
TRUE termination request pending.
FALSE termination request not pending.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 298 of file ch.cpp.
References chThdShouldTerminate.
void chibios_rt::BaseThread::sleep (systime_t interval) static
Suspends the invoking thread for the specified time.
Parameters
[in] interval the delay in system ticks, the special values are handled as follow:
TIME_INFINITE the thread enters an infinite sleep state.
TIME_IMMEDIATE this value is not allowed.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 303 of file ch.cpp.
References chThdSleep().
void chibios_rt::BaseThread::sleepUntil (systime_t time) static
Suspends the invoking thread until the system time arrives to the specified value.
Parameters
[in] time absolute system time
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 308 of file ch.cpp.
References chThdSleepUntil().
void chibios_rt::BaseThread::yield (void) static
Yields the time slot.
Yields the CPU control to the next thread in the ready list with equal priority, if any.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 313 of file ch.cpp.
References chThdYield().
static ThreadReference chibios_rt::BaseThread::waitMessage (void) static
Waits for a message.
Returns
The sender thread.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::getAndClearEvents (eventmask_t mask) static
Clears the pending events specified in the mask.
Parameters
[in] mask the events to be cleared
Returns
The pending events that were cleared.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::addEvents (eventmask_t mask) static
Adds (OR) a set of event flags on the current thread, this is much faster than using chEvtBroadcast() or chEvtSignal().
Parameters
[in] mask the event flags to be added
Returns
The current pending events mask.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitOneEvent (eventmask_t ewmask) static
Waits for a single event.
A pending event among those specified in ewmask is selected, cleared and its mask returned.
Note
One and only one event is served in the function, the one with the lowest event id. The function is meant to be invoked into a loop in order to serve all the pending events.
This means that Event Listeners with a lower event identifier have an higher priority.
Parameters
[in] ewmask mask of the events that the function should wait for, ALL_EVENTS enables all the events
Returns
The mask of the lowest id served and cleared event.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitAnyEvent (eventmask_t ewmask) static
Waits for any of the specified events.
The function waits for any event among those specified in ewmask to become pending then the events are cleared and returned.
Parameters
[in] ewmask mask of the events that the function should wait for, ALL_EVENTS enables all the events
Returns
The mask of the served and cleared events.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitAllEvents (eventmask_t ewmask) static
Waits for all the specified event flags then clears them.
The function waits for all the events specified in ewmask to become pending then the events are cleared and returned.
Parameters
[in] ewmask mask of the event ids that the function should wait for
Returns
The mask of the served and cleared events.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitOneEventTimeout (eventmask_t ewmask, systime_t time) static
Waits for a single event.
A pending event among those specified in ewmask is selected, cleared and its mask returned.
Note
One and only one event is served in the function, the one with the lowest event id. The function is meant to be invoked into a loop in order to serve all the pending events.
This means that Event Listeners with a lower event identifier have an higher priority.
Parameters
[in] ewmask mask of the events that the function should wait for, ALL_EVENTS enables all the events
[in] time the number of ticks before the operation timouts
Returns
The mask of the lowest id served and cleared event.
Return values
0 if the specified timeout expired.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitAnyEventTimeout (eventmask_t ewmask, systime_t time) static
Waits for any of the specified events.
The function waits for any event among those specified in ewmask to become pending then the events are cleared and returned.
Parameters
[in] ewmask mask of the events that the function should wait for, ALL_EVENTS enables all the events
[in] time the number of ticks before the operation timouts
Returns
The mask of the served and cleared events.
Return values
0 if the specified timeout expired.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static eventmask_t chibios_rt::BaseThread::waitAllEventsTimeout (eventmask_t ewmask, systime_t time) static
Waits for all the specified event flags then clears them.
The function waits for all the events specified in ewmask to become pending then the events are cleared and returned.
Parameters
[in] ewmask mask of the event ids that the function should wait for
[in] time the number of ticks before the operation timouts
Returns
The mask of the served and cleared events.
Return values
0 if the specified timeout expired.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static void chibios_rt::BaseThread::dispatchEvents (const evhandler_t handlers[], eventmask_t mask) static
Invokes the event handlers associated to an event flags mask.
Parameters
[in] mask mask of the event flags to be dispatched
[in] handlers an array of evhandler_t. The array must have size equal to the number of bits in eventmask_t.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static void chibios_rt::BaseThread::unlockMutex (void) static
Unlocks the next owned mutex in reverse lock order.
Precondition
The invoking thread must have at least one owned mutex.
Postcondition
The mutex is unlocked and removed from the per-thread stack of owned mutexes.
Returns
A pointer to the unlocked mutex.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
static void chibios_rt::BaseThread::unlockMutexS (void) static
Unlocks the next owned mutex in reverse lock order.
Precondition
The invoking thread must have at least one owned mutex.
Postcondition
The mutex is unlocked and removed from the per-thread stack of owned mutexes.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel.
Returns
A pointer to the unlocked mutex.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
static void chibios_rt::BaseThread::unlockAllMutexes (void) static
Unlocks all the mutexes owned by the invoking thread.
Postcondition
The stack of owned mutexes is emptied and all the found mutexes are unlocked.
Note
This function is MUCH MORE efficient than releasing the mutexes one by one and not just because the call overhead, this function does not have any overhead related to the priority inheritance mechanism.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.