RTC time conversion utilities
RTC time conversion utilities
Various
Detailed Description
RTC time conversion utilities.
Functions
void rtcGetTimeTm (RTCDriver *rtcp, struct tm *timp)
Gets raw time from RTC and converts it to canonicalized format.
void rtcSetTimeTm (RTCDriver *rtcp, struct tm *timp)
Sets RTC time.
time_t rtcGetTimeUnixSec (RTCDriver *rtcp)
Gets raw time from RTC and converts it to unix format.
void rtcSetTimeUnixSec (RTCDriver *rtcp, time_t tv_sec)
Sets RTC time.
uint64_t rtcGetTimeUnixUsec (RTCDriver *rtcp)
Gets raw time from RTC and converts it to unix format.
uint32_t rtcGetTimeFatFromCounter (RTCDriver *rtcp)
Get current time in format suitable for usage in FatFS.
uint32_t rtcGetTimeFat (RTCDriver *rtcp)
Get current time in format suitable for usage in FatFS.
Function Documentation
void rtcGetTimeTm (RTCDriver * rtcp, struct tm * timp)
Gets raw time from RTC and converts it to canonicalized format.
Parameters
[in] rtcp pointer to RTC driver structure
[out] timp pointer to a tm structure as defined in time.h
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 256 of file chrtclib.c.
References rtcGetTime().
Referenced by rtcGetTimeFatFromCounter().
void rtcSetTimeTm (RTCDriver * rtcp, struct tm * timp)
Sets RTC time.
Parameters
[in] rtcp pointer to RTC driver structure
[out] timp pointer to a tm structure as defined in time.h
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 271 of file chrtclib.c.
References rtcSetTime().
time_t rtcGetTimeUnixSec (RTCDriver * rtcp)
Gets raw time from RTC and converts it to unix format.
Parameters
[in] rtcp pointer to RTC driver structure
Returns
Unix time value in seconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 289 of file chrtclib.c.
References rtcGetTime().
Referenced by rtcGetTimeUnixUsec().
void rtcSetTimeUnixSec (RTCDriver * rtcp, time_t tv_sec)
Sets RTC time.
Parameters
[in] rtcp pointer to RTC driver structure
[in] tv_sec time specification
Returns
Unix time value in seconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 305 of file chrtclib.c.
References rtcSetTime().
uint64_t rtcGetTimeUnixUsec (RTCDriver * rtcp)
Gets raw time from RTC and converts it to unix format.
Parameters
[in] rtcp pointer to RTC driver structure
Returns
Unix time value in microseconds.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 323 of file chrtclib.c.
References rtcGetTime(), and rtcGetTimeUnixSec().
uint32_t rtcGetTimeFatFromCounter (RTCDriver * rtcp)
Get current time in format suitable for usage in FatFS.
Parameters
[in] rtcp pointer to RTC driver structure
Returns
FAT time value.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 344 of file chrtclib.c.
References rtcGetTimeTm().
uint32_t rtcGetTimeFat (RTCDriver * rtcp)
Get current time in format suitable for usage in FatFS.
Parameters
[in] rtcp pointer to RTC driver structure
Returns
FAT time value.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 185 of file rtc.c.
References chDbgCheck.