RTC Driver
RTC Driver
HAL
Detailed Description
Real Time Clock Abstraction Layer.
This module defines an abstract interface for a Real Time Clock Peripheral.
Precondition
In order to use the RTC driver the HAL_USE_RTC option must be enabled in halconf.h.
Functions
void rtcInit (void)
RTC Driver initialization.
void rtcSetTime (RTCDriver *rtcp, const RTCTime *timespec)
Set current time.
void rtcGetTime (RTCDriver *rtcp, RTCTime *timespec)
Get current time.
uint32_t rtcGetTimeFat (RTCDriver *rtcp)
Get current time in format suitable for usage in FatFS.
void rtcSetAlarm (RTCDriver *rtcp, rtcalarm_t alarm, const RTCAlarm *alarmspec)
Set alarm time.
void rtcGetAlarm (RTCDriver *rtcp, rtcalarm_t alarm, RTCAlarm *alarmspec)
Get current alarm.
void rtcSetCallback (RTCDriver *rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
Date/Time bit masks
#define RTC_TIME_SECONDS_MASK 0x0000001F /* @brief Seconds mask. */
#define RTC_TIME_MINUTES_MASK 0x000007E0 /* @brief Minutes mask. */
#define RTC_TIME_HOURS_MASK 0x0000F800 /* @brief Hours mask. */
#define RTC_DATE_DAYS_MASK 0x001F0000 /* @brief Days mask. */
#define RTC_DATE_MONTHS_MASK 0x01E00000 /* @brief Months mask. */
#define RTC_DATE_YEARS_MASK 0xFE000000 /* @brief Years mask. */
Macros
#define rtcSetTimeI(rtcp, timespec) rtc_lld_set_time(rtcp, timespec)
Set current time.
#define rtcGetTimeI(rtcp, timespec) rtc_lld_get_time(rtcp, timespec)
Get current time.
#define rtcSetAlarmI(rtcp, alarm, alarmspec) rtc_lld_set_alarm(rtcp, alarm, alarmspec)
Set alarm time.
#define rtcGetAlarmI(rtcp, alarm, alarmspec) rtc_lld_get_alarm(rtcp, alarm, alarmspec)
Get current alarm.
#define rtcSetCallbackI(rtcp, callback) rtc_lld_set_callback(rtcp, callback)
Enables or disables RTC callbacks.
Typedefs
typedef struct RTCDriver RTCDriver
Type of a structure representing an RTC driver.
typedef struct RTCTime RTCTime
Type of a structure representing an RTC time stamp.
Function Documentation
void rtcInit (void)
RTC Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 72 of file rtc.c.
Referenced by halInit().
void rtcSetTime (RTCDriver * rtcp, const RTCTime * timespec)
Set current time.
Parameters
[in] rtcp pointer to RTC driver structure
[in] timespec pointer to a RTCTime structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 85 of file rtc.c.
References chDbgCheck, chSysLock, chSysUnlock, and rtcSetTimeI.
Referenced by rtcSetTimeTm(), and rtcSetTimeUnixSec().
void rtcGetTime (RTCDriver * rtcp, RTCTime * timespec)
Get current time.
Parameters
[in] rtcp pointer to RTC driver structure
[out] timespec pointer to a RTCTime structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 102 of file rtc.c.
References chDbgCheck, chSysLock, chSysUnlock, and rtcGetTimeI.
Referenced by rtcGetTimeTm(), rtcGetTimeUnixSec(), and rtcGetTimeUnixUsec().
uint32_t rtcGetTimeFat (RTCDriver * rtcp)
Get current time in format suitable for usage in FatFS.
Parameters
[in] rtcp pointer to RTC driver structure
Returns
FAT time value.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 185 of file rtc.c.
References chDbgCheck.
void rtcSetAlarm (RTCDriver * rtcp, rtcalarm_t alarm, const RTCAlarm * alarmspec)
Set alarm time.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[in] alarmspec pointer to a RTCAlarm structure or NULL
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 121 of file rtc.c.
References chDbgCheck, chSysLock, chSysUnlock, and rtcSetAlarmI.
void rtcGetAlarm (RTCDriver * rtcp, rtcalarm_t alarm, RTCAlarm * alarmspec)
Get current alarm.
Note
If an alarm has not been set then the returned alarm specification is not meaningful.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[out] alarmspec pointer to a RTCAlarm structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 143 of file rtc.c.
References chDbgCheck, chSysLock, chSysUnlock, and rtcGetAlarmI.
void rtcSetCallback (RTCDriver * rtcp, rtccb_t callback)
Enables or disables RTC callbacks.
This function enables or disables the callback, use a NULL pointer in order to disable it.
Parameters
[in] rtcp pointer to RTC driver structure
[in] callback callback function pointer or NULL
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 167 of file rtc.c.
References chDbgCheck, chSysLock, chSysUnlock, and rtcSetCallbackI.
Macro Definition Documentation
#define rtcSetTimeI (rtcp, timespec) rtc_lld_set_time(rtcp, timespec)
Set current time.
Parameters
[in] rtcp pointer to RTC driver structure
[in] timespec pointer to a RTCTime structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 97 of file rtc.h.
Referenced by rtcSetTime().
#define rtcGetTimeI (rtcp, timespec) rtc_lld_get_time(rtcp, timespec)
Get current time.
Parameters
[in] rtcp pointer to RTC driver structure
[out] timespec pointer to a RTCTime structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 107 of file rtc.h.
Referenced by rtcGetTime().
#define rtcSetAlarmI (rtcp, alarm, alarmspec) rtc_lld_set_alarm(rtcp, alarm, alarmspec)
Set alarm time.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[in] alarmspec pointer to a RTCAlarm structure or NULL
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 119 of file rtc.h.
Referenced by rtcSetAlarm().
#define rtcGetAlarmI (rtcp, alarm, alarmspec) rtc_lld_get_alarm(rtcp, alarm, alarmspec)
Get current alarm.
Note
If an alarm has not been set then the returned alarm specification is not meaningful.
Parameters
[in] rtcp pointer to RTC driver structure
[in] alarm alarm identifier
[out] alarmspec pointer to a RTCAlarm structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 133 of file rtc.h.
Referenced by rtcGetAlarm().
#define rtcSetCallbackI (rtcp, callback) rtc_lld_set_callback(rtcp, callback)
Enables or disables RTC callbacks.
This function enables or disables the callback, use a NULL pointer in order to disable it.
Parameters
[in] rtcp pointer to RTC driver structure
[in] callback callback function pointer or NULL
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 148 of file rtc.h.
Referenced by rtcSetCallback().
Typedef Documentation
typedef struct RTCDriver RTCDriver
Type of a structure representing an RTC driver.
Definition at line 76 of file rtc.h.
typedef struct RTCTime RTCTime
Type of a structure representing an RTC time stamp.
Definition at line 81 of file rtc.h.