Counting Semaphores
Counting Semaphores
Kernel » Synchronization
Detailed Description
Semaphores related APIs and services.
     <h2>Operation mode</h2>
     Semaphores are a flexible synchronization primitive, ChibiOS/RT
     implements semaphores in their "counting semaphores" variant as
     defined by Edsger Dijkstra plus several enhancements like:
     - Wait operation with timeout.
     - Reset operation.
     - Atomic wait+signal operation.
     - Return message from the wait operation (OK, RESET, TIMEOUT).
     .
     The binary semaphores variant can be easily implemented using
     counting semaphores.<br>
     Operations defined for semaphores:
     - <b>Signal</b>: The semaphore counter is increased and if the
       result is non-positive then a waiting thread is removed from
       the semaphore queue and made ready for execution.
     - <b>Wait</b>: The semaphore counter is decreased and if the result
       becomes negative the thread is queued in the semaphore and
       suspended.
     - <b>Reset</b>: The semaphore counter is reset to a non-negative
       value and all the threads in the queue are released.
     .
     Semaphores can be used as guards for mutual exclusion zones
     (note that mutexes are recommended for this kind of use) but
     also have other uses, queues guards and counters for example.<br>
     Semaphores usually use a FIFO queuing strategy but it is possible
     to make them order threads by priority by enabling
     @p CH_USE_SEMAPHORES_PRIORITY in @p chconf.h.
Precondition
In order to use the semaphore APIs the CH_USE_SEMAPHORES option must be enabled in chconf.h.
Data Structures
struct Semaphore
Semaphore structure.
Functions
void chSemInit (Semaphore *sp, cnt_t n)
Initializes a semaphore with the specified counter value.
void chSemReset (Semaphore *sp, cnt_t n)
Performs a reset operation on the semaphore.
void chSemResetI (Semaphore *sp, cnt_t n)
Performs a reset operation on the semaphore.
msg_t chSemWait (Semaphore *sp)
Performs a wait operation on a semaphore.
msg_t chSemWaitS (Semaphore *sp)
Performs a wait operation on a semaphore.
msg_t chSemWaitTimeout (Semaphore *sp, systime_t time)
Performs a wait operation on a semaphore with timeout specification.
msg_t chSemWaitTimeoutS (Semaphore *sp, systime_t time)
Performs a wait operation on a semaphore with timeout specification.
void chSemSignal (Semaphore *sp)
Performs a signal operation on a semaphore.
void chSemSignalI (Semaphore *sp)
Performs a signal operation on a semaphore.
void chSemAddCounterI (Semaphore *sp, cnt_t n)
Adds the specified value to the semaphore counter.
msg_t chSemSignalWait (Semaphore *sps, Semaphore *spw)
Performs atomic signal and wait operations on two semaphores.
Macro Functions
#define chSemFastWaitI(sp) ((sp)->s_cnt--)
Decreases the semaphore counter.
#define chSemFastSignalI(sp) ((sp)->s_cnt++)
Increases the semaphore counter.
#define chSemGetCounterI(sp) ((sp)->s_cnt)
Returns the semaphore counter current value.
Macros
#define _SEMAPHORE_DATA(name, n) {_THREADSQUEUE_DATA(name.s_queue), n}
Data part of a static semaphore initializer.
#define SEMAPHORE_DECL(name, n) Semaphore name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Typedefs
typedef struct Semaphore Semaphore
Semaphore structure.
Function Documentation
void chSemInit (Semaphore * sp, cnt_t n)
Initializes a semaphore with the specified counter value.
Parameters
[out] sp pointer to a Semaphore structure
[in] n initial value of the semaphore counter. Must be non-negative.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 86 of file chsem.c.
References chDbgCheck, queue_init, Semaphore::s_cnt, and Semaphore::s_queue.
Referenced by _heap_init(), adcObjectInit(), canObjectInit(), chHeapInit(), chMBInit(), i2cObjectInit(), macObjectInit(), and spiObjectInit().
void chSemReset (Semaphore * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
Note
The released threads can recognize they were waked up by a reset rather than a signal because the chSemWait() will return RDY_RESET instead of RDY_OK.
Parameters
[in] sp pointer to a Semaphore structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 109 of file chsem.c.
References chSchRescheduleS(), chSemResetI(), chSysLock, and chSysUnlock.
void chSemResetI (Semaphore * sp, cnt_t n)
Performs a reset operation on the semaphore.
Postcondition
After invoking this function all the threads waiting on the semaphore, if any, are released and the semaphore counter is set to the specified, non negative, value.
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Note
The released threads can recognize they were waked up by a reset rather than a signal because the chSemWait() will return RDY_RESET instead of RDY_OK.
Parameters
[in] sp pointer to a Semaphore structure
[in] n the new value of the semaphore counter. The value must be non-negative.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 136 of file chsem.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), chSchReadyI(), isempty, lifo_remove(), notempty, Thread::p_u, RDY_RESET, Thread::rdymsg, Semaphore::s_cnt, and Semaphore::s_queue.
Referenced by canStop(), chMBReset(), and chSemReset().
msg_t chSemWait (Semaphore * sp)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a Semaphore structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
RDY_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
RDY_RESET if the semaphore has been reset using chSemReset().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 164 of file chsem.c.
References chSemWaitS(), chSysLock, and chSysUnlock.
Referenced by adcAcquireBus(), i2cAcquireBus(), and spiAcquireBus().
msg_t chSemWaitS (Semaphore * sp)
Performs a wait operation on a semaphore.
Parameters
[in] sp pointer to a Semaphore structure
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
RDY_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
RDY_RESET if the semaphore has been reset using chSemReset().
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 185 of file chsem.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassS(), chSchGoSleepS(), currp, isempty, notempty, RDY_OK, Semaphore::s_cnt, Semaphore::s_queue, and THD_STATE_WTSEM.
Referenced by chSemWait().
msg_t chSemWaitTimeout (Semaphore * sp, systime_t time)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a Semaphore structure
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
RDY_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
RDY_RESET if the semaphore has been reset using chSemReset().
RDY_TIMEOUT if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 222 of file chsem.c.
References chSemWaitTimeoutS(), chSysLock, and chSysUnlock.
msg_t chSemWaitTimeoutS (Semaphore * sp, systime_t time)
Performs a wait operation on a semaphore with timeout specification.
Parameters
[in] sp pointer to a Semaphore structure
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
RDY_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
RDY_RESET if the semaphore has been reset using chSemReset().
RDY_TIMEOUT if the semaphore has not been signaled or reset within the specified timeout.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 250 of file chsem.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassS(), chSchGoSleepTimeoutS(), currp, isempty, notempty, RDY_OK, RDY_TIMEOUT, Semaphore::s_cnt, Semaphore::s_queue, THD_STATE_WTSEM, and TIME_IMMEDIATE.
Referenced by canReceive(), canTransmit(), chMBFetchS(), chMBPostAheadS(), chMBPostS(), chSemWaitTimeout(), macWaitReceiveDescriptor(), and macWaitTransmitDescriptor().
void chSemSignal (Semaphore * sp)
Performs a signal operation on a semaphore.
Parameters
[in] sp pointer to a Semaphore structure
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 278 of file chsem.c.
References chDbgAssert, chDbgCheck, chSchWakeupS(), chSysLock, chSysUnlock, fifo_remove(), isempty, notempty, RDY_OK, Semaphore::s_cnt, and Semaphore::s_queue.
Referenced by adcReleaseBus(), i2cReleaseBus(), and spiReleaseBus().
void chSemSignalI (Semaphore * sp)
Performs a signal operation on a semaphore.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a Semaphore structure
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 303 of file chsem.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), chSchReadyI(), fifo_remove(), isempty, notempty, Thread::p_u, RDY_OK, Thread::rdymsg, Semaphore::s_cnt, and Semaphore::s_queue.
Referenced by chMBFetchI(), chMBFetchS(), chMBPostAheadI(), chMBPostAheadS(), chMBPostI(), and chMBPostS().
void chSemAddCounterI (Semaphore * sp, cnt_t n)
Adds the specified value to the semaphore counter.
Postcondition
This function does not reschedule so a call to a rescheduling function must be performed before unlocking the kernel. Note that interrupt handlers always reschedule on exit so an explicit reschedule must not be performed in ISRs.
Parameters
[in] sp pointer to a Semaphore structure
[in] n value to be added to the semaphore counter. The value must be positive.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 334 of file chsem.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), chSchReadyI(), fifo_remove(), isempty, notempty, Thread::p_u, RDY_OK, Thread::rdymsg, Semaphore::s_cnt, and Semaphore::s_queue.
msg_t chSemSignalWait (Semaphore * sps, Semaphore * spw)
Performs atomic signal and wait operations on two semaphores.
Precondition
The configuration option CH_USE_SEMSW must be enabled in order to use this function.
Parameters
[in] sps pointer to a Semaphore structure to be signaled
[in] spw pointer to a Semaphore structure to wait on
Returns
A message specifying how the invoking thread has been released from the semaphore.
Return values
RDY_OK if the thread has not stopped on the semaphore or the semaphore has been signaled.
RDY_RESET if the semaphore has been reset using chSemReset().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 366 of file chsem.c.
References chDbgAssert, chDbgCheck, chSchGoSleepS(), chSchReadyI(), chSchRescheduleS(), chSysLock, chSysUnlock, currp, fifo_remove(), isempty, notempty, Thread::p_u, RDY_OK, Thread::rdymsg, Semaphore::s_cnt, Semaphore::s_queue, THD_STATE_WTSEM, and Thread::wtobjp.
Macro Definition Documentation
#define _SEMAPHORE_DATA (name, n) {_THREADSQUEUE_DATA(name.s_queue), n}
Data part of a static semaphore initializer.
This macro should be used when statically initializing a semaphore that is part of a bigger structure.
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 79 of file chsem.h.
#define SEMAPHORE_DECL (name, n) Semaphore name = _SEMAPHORE_DATA(name, n)
Static semaphore initializer.
Statically initialized semaphores require no explicit initialization using chSemInit().
Parameters
[in] name the name of the semaphore variable
[in] n the counter initial value, this value must be non-negative
Definition at line 90 of file chsem.h.
#define chSemFastWaitI (sp) ((sp)->s_cnt--)
Decreases the semaphore counter.
This macro can be used when the counter is known to be positive.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 102 of file chsem.h.
Referenced by chMBFetchI(), chMBPostAheadI(), and chMBPostI().
#define chSemFastSignalI (sp) ((sp)->s_cnt++)
Increases the semaphore counter.
This macro can be used when the counter is known to be not negative.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 111 of file chsem.h.
#define chSemGetCounterI (sp) ((sp)->s_cnt)
Returns the semaphore counter current value.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 118 of file chsem.h.
Referenced by chMBFetchI(), chMBPostAheadI(), and chMBPostI().
Typedef Documentation
typedef struct Semaphore Semaphore
Semaphore structure.