Mailboxes
Mailboxes
Kernel » Synchronization
Detailed Description
Asynchronous messages.
Operation mode
A mailbox is an asynchronous communication mechanism.
Operations defined for mailboxes:
Post: Posts a message on the mailbox in FIFO order.
Post Ahead: Posts a message on the mailbox with urgent priority.
Fetch: A message is fetched from the mailbox and removed from the queue.
Reset: The mailbox is emptied and all the stored messages are lost.
A message is a variable of type msg_t that is guaranteed to have the same size of and be compatible with (data) pointers (anyway an explicit cast is needed). If larger messages need to be exchanged then a pointer to a structure can be posted in the mailbox but the posting side has no predefined way to know when the message has been processed. A possible approach is to allocate memory (from a memory pool for example) from the posting side and free it on the fetching side. Another approach is to set a "done" flag into the structure pointed by the message.
Precondition
In order to use the mailboxes APIs the CH_USE_MAILBOXES option must be enabled in chconf.h.
Data Structures
struct Mailbox
Structure representing a mailbox object.
Functions
void chMBInit (Mailbox *mbp, msg_t *buf, cnt_t n)
Initializes a Mailbox object.
void chMBReset (Mailbox *mbp)
Resets a Mailbox object.
msg_t chMBPost (Mailbox *mbp, msg_t msg, systime_t time)
Posts a message into a mailbox.
msg_t chMBPostS (Mailbox *mbp, msg_t msg, systime_t time)
Posts a message into a mailbox.
msg_t chMBPostI (Mailbox *mbp, msg_t msg)
Posts a message into a mailbox.
msg_t chMBPostAhead (Mailbox *mbp, msg_t msg, systime_t time)
Posts an high priority message into a mailbox.
msg_t chMBPostAheadS (Mailbox *mbp, msg_t msg, systime_t time)
Posts an high priority message into a mailbox.
msg_t chMBPostAheadI (Mailbox *mbp, msg_t msg)
Posts an high priority message into a mailbox.
msg_t chMBFetch (Mailbox *mbp, msg_t *msgp, systime_t time)
Retrieves a message from a mailbox.
msg_t chMBFetchS (Mailbox *mbp, msg_t *msgp, systime_t time)
Retrieves a message from a mailbox.
msg_t chMBFetchI (Mailbox *mbp, msg_t *msgp)
Retrieves a message from a mailbox.
Macro Functions
#define chMBSizeI(mbp) ((mbp)->mb_top - (mbp)->mb_buffer)
Returns the mailbox buffer size.
#define chMBGetFreeCountI(mbp) chSemGetCounterI(&(mbp)->mb_emptysem)
Returns the number of free message slots into a mailbox.
#define chMBGetUsedCountI(mbp) chSemGetCounterI(&(mbp)->mb_fullsem)
Returns the number of used message slots into a mailbox.
#define chMBPeekI(mbp) (*(mbp)->mb_rdptr)
Returns the next message in the queue without removing it.
Macros
#define _MAILBOX_DATA(name, buffer, size)
Data part of a static mailbox initializer.
#define MAILBOX_DECL(name, buffer, size) Mailbox name = _MAILBOX_DATA(name, buffer, size)
Static mailbox initializer.
Function Documentation
void chMBInit (Mailbox * mbp, msg_t * buf, cnt_t n)
Initializes a Mailbox object.
Parameters
[out] mbp the pointer to the Mailbox structure to be initialized
[in] buf pointer to the messages buffer as an array of msg_t
[in] n number of elements in the buffer array
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 72 of file chmboxes.c.
References chDbgCheck, chSemInit(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, and Mailbox::mb_wrptr.
void chMBReset (Mailbox * mbp)
Resets a Mailbox object.
All the waiting threads are resumed with status RDY_RESET and the queued messages are lost.
Parameters
[in] mbp the pointer to an initialized Mailbox object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 91 of file chmboxes.c.
References chDbgCheck, chSchRescheduleS(), chSemResetI(), chSysLock, chSysUnlock, Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, and Mailbox::mb_wrptr.
msg_t chMBPost (Mailbox * mbp, msg_t msg, systime_t time)
Posts a message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 122 of file chmboxes.c.
References chMBPostS(), chSysLock, and chSysUnlock.
msg_t chMBPostS (Mailbox * mbp, msg_t msg, systime_t time)
Posts a message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 150 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_top, Mailbox::mb_wrptr, and RDY_OK.
Referenced by chMBPost().
msg_t chMBPostI (Mailbox * mbp, msg_t msg)
Posts a message into a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is full.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_TIMEOUT if the mailbox is full and the message cannot be posted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 181 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_top, Mailbox::mb_wrptr, RDY_OK, and RDY_TIMEOUT.
msg_t chMBPostAhead (Mailbox * mbp, msg_t msg, systime_t time)
Posts an high priority message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 215 of file chmboxes.c.
References chMBPostAheadS(), chSysLock, and chSysUnlock.
msg_t chMBPostAheadS (Mailbox * mbp, msg_t msg, systime_t time)
Posts an high priority message into a mailbox.
The invoking thread waits until a empty slot in the mailbox becomes available or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 243 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, and RDY_OK.
Referenced by chMBPostAhead().
msg_t chMBPostAheadI (Mailbox * mbp, msg_t msg)
Posts an high priority message into a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is full.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[in] msg the message to be posted on the mailbox
Returns
The operation status.
Return values
RDY_OK if a message has been correctly posted.
RDY_TIMEOUT if the mailbox is full and the message cannot be posted.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 274 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, RDY_OK, and RDY_TIMEOUT.
msg_t chMBFetch (Mailbox * mbp, msg_t * msgp, systime_t time)
Retrieves a message from a mailbox.
The invoking thread waits until a message is posted in the mailbox or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[out] msgp pointer to a message variable for the received message
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly fetched.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 308 of file chmboxes.c.
References chMBFetchS(), chSysLock, and chSysUnlock.
msg_t chMBFetchS (Mailbox * mbp, msg_t * msgp, systime_t time)
Retrieves a message from a mailbox.
The invoking thread waits until a message is posted in the mailbox or the specified time runs out.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[out] msgp pointer to a message variable for the received message
[in] time the number of ticks before the operation timeouts, the following special values are allowed:
TIME_IMMEDIATE immediate timeout.
TIME_INFINITE no timeout.
Returns
The operation status.
Return values
RDY_OK if a message has been correctly fetched.
RDY_RESET if the mailbox has been reset while waiting.
RDY_TIMEOUT if the operation has timed out.
Function Class:
This is an S-Class API, this function can be invoked from within a system lock zone by threads only.
Definition at line 336 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassS(), chSchRescheduleS(), chSemSignalI(), chSemWaitTimeoutS(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, and RDY_OK.
Referenced by chMBFetch().
msg_t chMBFetchI (Mailbox * mbp, msg_t * msgp)
Retrieves a message from a mailbox.
This variant is non-blocking, the function returns a timeout condition if the queue is empty.
Parameters
[in] mbp the pointer to an initialized Mailbox object
[out] msgp pointer to a message variable for the received message
Returns
The operation status.
Return values
RDY_OK if a message has been correctly fetched.
RDY_TIMEOUT if the mailbox is empty and a message cannot be fetched.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 367 of file chmboxes.c.
References chDbgCheck, chDbgCheckClassI(), chSemFastWaitI, chSemGetCounterI, chSemSignalI(), Mailbox::mb_buffer, Mailbox::mb_emptysem, Mailbox::mb_fullsem, Mailbox::mb_rdptr, Mailbox::mb_top, RDY_OK, and RDY_TIMEOUT.
Macro Definition Documentation
#define chMBSizeI (mbp) ((mbp)->mb_top - (mbp)->mb_buffer)
Returns the mailbox buffer size.
Parameters
[in] mbp the pointer to an initialized Mailbox object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 93 of file chmboxes.h.
#define chMBGetFreeCountI (mbp) chSemGetCounterI(&(mbp)->mb_emptysem)
Returns the number of free message slots into a mailbox.
Note
Can be invoked in any system state but if invoked out of a locked state then the returned value may change after reading.
The returned value can be less than zero when there are waiting threads on the internal semaphore.
Parameters
[in] mbp the pointer to an initialized Mailbox object
Returns
The number of empty message slots.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 108 of file chmboxes.h.
#define chMBGetUsedCountI (mbp) chSemGetCounterI(&(mbp)->mb_fullsem)
Returns the number of used message slots into a mailbox.
Note
Can be invoked in any system state but if invoked out of a locked state then the returned value may change after reading.
The returned value can be less than zero when there are waiting threads on the internal semaphore.
Parameters
[in] mbp the pointer to an initialized Mailbox object
Returns
The number of queued messages.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 122 of file chmboxes.h.
#define chMBPeekI (mbp) (*(mbp)->mb_rdptr)
Returns the next message in the queue without removing it.
Precondition
A message must be waiting in the queue for this function to work or it would return garbage. The correct way to use this macro is to use chMBGetFullCountI() and then use this macro, all within a lock state.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 133 of file chmboxes.h.
#define _MAILBOX_DATA (name, buffer, size)
Value:
{                             \
  (msg_t *)(buffer),                                                    \
  (msg_t *)(buffer) + size,                                             \
  (msg_t *)(buffer),                                                    \
  (msg_t *)(buffer),                                                    \
  _SEMAPHORE_DATA(name.mb_fullsem, 0),                                  \
  _SEMAPHORE_DATA(name.mb_emptysem, size),                              \
}
Data part of a static mailbox initializer.
This macro should be used when statically initializing a mailbox that is part of a bigger structure.
Parameters
[in] name the name of the mailbox variable
[in] buffer pointer to the mailbox buffer area
[in] size size of the mailbox buffer area
Definition at line 145 of file chmboxes.h.
#define MAILBOX_DECL (name, buffer, size) Mailbox name = _MAILBOX_DATA(name, buffer, size)
Static mailbox initializer.
Statically initialized mailboxes require no explicit initialization using chMBInit().
Parameters
[in] name the name of the mailbox variable
[in] buffer pointer to the mailbox buffer area
[in] size size of the mailbox buffer area
Definition at line 163 of file chmboxes.h.