Test Runtime
Test Runtime
Detailed Description
Runtime code for the test suite execution, this code is not part of the OS and should not be included in user applications.
Data Structures
struct testcase
Structure representing a test case.
Functions
void test_printn (uint32_t n)
Prints a decimal unsigned number.
void test_print (const char *msgp)
Prints a line without final end-of-line.
void test_println (const char *msgp)
Prints a line.
void test_emit_token (char token)
Emits a token into the tokens buffer.
void test_terminate_threads (void)
Sets a termination request in all the test-spawned threads.
void test_wait_threads (void)
Waits for the completion of all the test-spawned threads.
systime_t test_wait_tick (void)
Delays execution until next system time tick.
void test_start_timer (unsigned ms)
Starts the test timer.
msg_t TestThread (void *p)
Test execution thread function.
Variables
bool_t test_timer_done
Set to TRUE when the test timer reaches its deadline.
Macros
#define DELAY_BETWEEN_TESTS 200
Delay inserted between test cases.
#define TEST_NO_BENCHMARKS FALSE
If TRUE then benchmarks are not included.
#define test_fail(point)
Test failure enforcement.
#define test_assert(point, condition, msg)
Test assertion.
#define test_assert_lock(point, condition, msg)
Test assertion with lock.
#define test_assert_sequence(point, expected)
Test sequence assertion.
#define test_assert_time_window(point, start, end)
Test time window assertion.
Function Documentation
void test_printn (uint32_t n)
Prints a decimal unsigned number.
Parameters
[in] n the number to be printed
Definition at line 91 of file test.c.
References chSequentialStreamPut.
Referenced by TestThread().
void test_print (const char * msgp)
Prints a line without final end-of-line.
Parameters
[in] msgp the message
Definition at line 110 of file test.c.
References chSequentialStreamPut.
Referenced by test_println(), and TestThread().
void test_println (const char * msgp)
Prints a line.
Parameters
[in] msgp the message
Definition at line 121 of file test.c.
References chSequentialStreamWrite, and test_print().
Referenced by TestThread().
void test_emit_token (char token)
Emits a token into the tokens buffer.
Parameters
[in] token the token as a char
Definition at line 147 of file test.c.
References chSysLock, and chSysUnlock.
void test_terminate_threads (void)
Sets a termination request in all the test-spawned threads.
Definition at line 196 of file test.c.
References chThdTerminate().
void test_wait_threads (void)
Waits for the completion of all the test-spawned threads.
Definition at line 207 of file test.c.
References chThdWait().
systime_t test_wait_tick (void)
Delays execution until next system time tick.
Returns
The system time.
Definition at line 245 of file test.c.
References chThdSleep(), and chTimeNow.
void test_start_timer (unsigned ms)
Starts the test timer.
Parameters
[in] ms time in milliseconds
Definition at line 272 of file test.c.
References chVTSet, FALSE, and MS2ST.
msg_t TestThread (void * p)
Test execution thread function.
Parameters
[in] p pointer to a BaseChannel object for test output
Returns
A failure boolean value.
Definition at line 314 of file test.c.
References CH_ARCHITECTURE_NAME, CH_COMPILER_NAME, CH_CORE_VARIANT_NAME, CH_KERNEL_VERSION, CH_PORT_INFO, chThdSleepMilliseconds, DELAY_BETWEEN_TESTS, FALSE, test_print(), test_println(), and test_printn().
Variable Documentation
bool_t test_timer_done
Set to TRUE when the test timer reaches its deadline.
Definition at line 258 of file test.c.
Macro Definition Documentation
#define DELAY_BETWEEN_TESTS 200
Delay inserted between test cases.
Definition at line 32 of file test.h.
Referenced by TestThread().
#define TEST_NO_BENCHMARKS FALSE
If TRUE then benchmarks are not included.
Definition at line 39 of file test.h.
#define test_fail (point)
Value:
{                                                  \
  _test_fail(point);                                                        \
  return;                                                                   \
}
Test failure enforcement.
Definition at line 108 of file test.h.
#define test_assert (point, condition, msg)
Value:
{                                \
  if (_test_assert(point, condition))                                       \
    return;                                                                 \
}
Test assertion.
Parameters
[in] point numeric assertion identifier
[in] condition a boolean expression that must be verified to be true
[in] msg failure message
Definition at line 120 of file test.h.
#define test_assert_lock (point, condition, msg)
Value:
{                           \
  chSysLock();                                                              \
  if (_test_assert(point, condition)) {                                     \
    chSysUnlock();                                                          \
    return;                                                                 \
  }                                                                         \
  chSysUnlock();                                                            \
}
Test assertion with lock.
Parameters
[in] point numeric assertion identifier
[in] condition a boolean expression that must be verified to be true
[in] msg failure message
Definition at line 132 of file test.h.
#define test_assert_sequence (point, expected)
Value:
{                             \
  if (_test_assert_sequence(point, expected))                               \
    return;                                                                 \
}
Test sequence assertion.
Parameters
[in] point numeric assertion identifier
[in] expected string to be matched with the tokens buffer
Definition at line 147 of file test.h.
#define test_assert_time_window (point, start, end)
Value:
{                        \
  if (_test_assert_time_window(point, start, end))                          \
    return;                                                                 \
}
Test time window assertion.
Parameters
[in] point numeric assertion identifier
[in] start initial time in the window (included)
[in] end final time in the window (not included)
Definition at line 159 of file test.h.