Interface module for LIS302DL MEMS
Interface module for LIS302DL MEMS
Detailed Description
Interface module for LIS302DL MEMS.
This module implements a generic interface for the LIS302DL STMicroelectronics MEMS device. The communication is performed through a standard SPI driver.
Functions
uint8_t lis302dlReadRegister (SPIDriver *spip, uint8_t reg)
Reads a register value.
void lis302dlWriteRegister (SPIDriver *spip, uint8_t reg, uint8_t value)
Writes a value into a register.
LIS302DL register names
#define LIS302DL_WHO_AM_I 0x0F
#define LIS302DL_CTRL_REG1 0x20
#define LIS302DL_CTRL_REG2 0x21
#define LIS302DL_CTRL_REG3 0x22
#define LIS302DL_HP_FILTER_RESET 0x23
#define LIS302DL_STATUS_REG 0x27
#define LIS302DL_OUTX 0x29
#define LIS302DL_OUTY 0x2B
#define LIS302DL_OUTZ 0x2D
#define LIS302DL_FF_WU_CFG1 0x30
#define LIS302DL_FF_WU_SRC1 0x31
#define LIS302DL_FF_WU_THS1 0x32
#define LIS302DL_FF_WU_DURATION1 0x33
#define LIS302DL_FF_WU_CFG2 0x34
#define LIS302DL_FF_WU_SRC2 0x35
#define LIS302DL_FF_WU_THS2 0x36
#define LIS302DL_FF_WU_DURATION2 0x37
#define LIS302DL_CLICK_CFG 0x38
#define LIS302DL_CLICK_SRC 0x39
#define LIS302DL_CLICK_THSY_X 0x3B
#define LIS302DL_CLICK_THSZ 0x3C
#define LIS302DL_CLICK_TIMELIMIT 0x3D
#define LIS302DL_CLICK_LATENCY 0x3E
#define LIS302DL_CLICK_WINDOW 0x3F
Function Documentation
uint8_t lis302dlReadRegister (SPIDriver * spip, uint8_t reg)
Reads a register value.
Precondition
The SPI interface must be initialized and the driver started.
Parameters
[in] spip pointer to the SPI initerface
[in] reg register number
Returns
The register value.
Definition at line 60 of file lis302dl.c.
References spiExchange(), spiSelect(), and spiUnselect().
void lis302dlWriteRegister (SPIDriver * spip, uint8_t reg, uint8_t value)
Writes a value into a register.
Precondition
The SPI interface must be initialized and the driver started.
Parameters
[in] spip pointer to the SPI initerface
[in] reg register number
[in] value the value to be written
Definition at line 78 of file lis302dl.c.
References chDbgAssert, FALSE, spiSelect(), spiSend(), and spiUnselect().