System formatted print
System formatted print
Various
Detailed Description
System formatted print service.
This module implements printf()-like function able to send data to any module implementing a BaseSequentialStream interface.
Functions
void chvprintf (BaseSequentialStream *chp, const char *fmt, va_list ap)
System formatted output function.
int chsnprintf (char *str, size_t size, const char *fmt,...)
System formatted output function.
Macros
#define CHPRINTF_USE_FLOAT FALSE
Float type support.
Function Documentation
void chvprintf (BaseSequentialStream * chp, const char * fmt, va_list ap)
System formatted output function.
This function implements a minimal vprintf()-like functionality with output on a BaseSequentialStream. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] chp pointer to a BaseSequentialStream implementing object
[in] fmt formatting string
[in] ap list of parameters
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 112 of file chprintf.c.
References chSequentialStreamPut, FALSE, and TRUE.
Referenced by chsnprintf().
int chsnprintf (char * str, size_t size, const char * fmt, ...)
System formatted output function.
This function implements a minimal vprintf()-like functionality with output on a BaseSequentialStream. The general parameters format is: %[-][width|*][.precision|*][l|L]p. The following parameter types (p) are supported:
x hexadecimal integer.
X hexadecimal long.
o octal integer.
O octal long.
d decimal signed integer.
D decimal signed long.
u decimal unsigned integer.
U decimal unsigned long.
c character.
s string.
Parameters
[in] str pointer to a buffer
[in] size maximum size of the buffer
[in] fmt formatting string
Returns
The size of the generated string.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 288 of file chprintf.c.
References chvprintf(), and msObjectInit().
Macro Definition Documentation
#define CHPRINTF_USE_FLOAT FALSE
Float type support.
Definition at line 34 of file chprintf.h.