PWM Driver
PWM Driver
HAL
Detailed Description
Generic PWM Driver.
This module implements a generic PWM (Pulse Width Modulation) driver.
Precondition
In order to use the PWM driver the HAL_USE_PWM option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
PWM Operations.
This driver abstracts a generic PWM timer composed of:
A clock prescaler.
A main up counter.
A comparator register that resets the main counter to zero when the limit is reached. An optional callback can be generated when this happens.
An array of PWM_CHANNELS PWM channels, each channel has an output, a comparator and is able to invoke an optional callback when a comparator match with the main counter happens.
A PWM channel output can be in two different states:
IDLE, when the channel is disabled or after a match occurred.
ACTIVE, when the channel is enabled and a match didn't occur yet in the current PWM cycle.
Note that the two states can be associated to both logical zero or one in the PWMChannelConfig structure.
Data Structures
struct PWMChannelConfig
PWM driver channel configuration structure.
struct PWMConfig
Driver configuration structure.
struct PWMDriver
Structure representing an PWM driver.
Functions
void pwmInit (void)
PWM Driver initialization.
void pwmObjectInit (PWMDriver *pwmp)
Initializes the standard part of a PWMDriver structure.
void pwmStart (PWMDriver *pwmp, const PWMConfig *config)
Configures and activates the PWM peripheral.
void pwmStop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
void pwmChangePeriod (PWMDriver *pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
void pwmEnableChannel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwmDisableChannel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel.
void pwm_lld_init (void)
Low level PWM driver initialization.
void pwm_lld_start (PWMDriver *pwmp)
Configures and activates the PWM peripheral.
void pwm_lld_stop (PWMDriver *pwmp)
Deactivates the PWM peripheral.
void pwm_lld_change_period (PWMDriver *pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
void pwm_lld_enable_channel (PWMDriver *pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
void pwm_lld_disable_channel (PWMDriver *pwmp, pwmchannel_t channel)
Disables a PWM channel.
Variables
PWMDriver PWMD1
PWM1 driver identifier.
PWM output mode macros
#define PWM_OUTPUT_MASK 0x0F
Standard output modes mask.
#define PWM_OUTPUT_DISABLED 0x00
Output not driven, callback only.
#define PWM_OUTPUT_ACTIVE_HIGH 0x01
Positive PWM logic, active is logic level one.
#define PWM_OUTPUT_ACTIVE_LOW 0x02
Inverse PWM logic, active is logic level zero.
PWM duty cycle conversion
#define PWM_FRACTION_TO_WIDTH(pwmp, denominator, numerator)
Converts from fraction to pulse width.
#define PWM_DEGREES_TO_WIDTH(pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
#define PWM_PERCENTAGE_TO_WIDTH(pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Macro Functions
#define pwmChangePeriodI(pwmp, value)
Changes the period the PWM peripheral.
#define pwmEnableChannelI(pwmp, channel, width) pwm_lld_enable_channel(pwmp, channel, width)
Enables a PWM channel.
#define pwmDisableChannelI(pwmp, channel) pwm_lld_disable_channel(pwmp, channel)
Disables a PWM channel.
#define pwmIsChannelEnabledI(pwmp, channel) pwm_lld_is_channel_enabled(pwmp, channel)
Returns a PWM channel status.
Configuration options
#define PLATFORM_PWM_USE_PWM1 FALSE
PWM driver enable switch.
Macros
#define PWM_CHANNELS 4
Number of PWM channels per PWM driver.
#define pwm_lld_is_channel_enabled(pwmp, channel) FALSE
Returns a PWM channel status.
Typedefs
typedef struct PWMDriver PWMDriver
Type of a structure representing a PWM driver.
typedef void(* pwmcallback_t) (PWMDriver *pwmp)
PWM notification callback type.
typedef uint32_t pwmmode_t
PWM mode type.
typedef uint8_t pwmchannel_t
PWM channel type.
typedef uint16_t pwmcnt_t
PWM counter type.
Enumerations
enum pwmstate_t { PWM_UNINIT = 0, PWM_STOP = 1, PWM_READY = 2 }
Driver state machine possible states.
Function Documentation
void pwmInit (void)
PWM Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file pwm.c.
References pwm_lld_init().
Referenced by halInit().
void pwmObjectInit (PWMDriver * pwmp)
Initializes the standard part of a PWMDriver structure.
Parameters
[out] pwmp pointer to a PWMDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 80 of file pwm.c.
References PWMDriver::config, PWM_STOP, and PWMDriver::state.
Referenced by pwm_lld_init().
void pwmStart (PWMDriver * pwmp, const PWMConfig * config)
Configures and activates the PWM peripheral.
Note
Starting a driver that is already in the PWM_READY state disables all the active channels.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] config pointer to a PWMConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 99 of file pwm.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, PWMDriver::config, PWMConfig::period, PWMDriver::period, pwm_lld_start(), PWM_READY, PWM_STOP, and PWMDriver::state.
void pwmStop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters
[in] pwmp pointer to a PWMDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 120 of file pwm.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, pwm_lld_stop(), PWM_READY, PWM_STOP, and PWMDriver::state.
void pwmChangePeriod (PWMDriver * pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] period new cycle time in ticks
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file pwm.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, PWM_READY, pwmChangePeriodI, and PWMDriver::state.
void pwmEnableChannel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
[in] width PWM pulse width as clock pulses number
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 172 of file pwm.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, PWM_CHANNELS, pwm_lld_enable_channel(), PWM_READY, and PWMDriver::state.
void pwmDisableChannel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 200 of file pwm.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, PWM_CHANNELS, pwm_lld_disable_channel(), PWM_READY, and PWMDriver::state.
void pwm_lld_init (void)
Low level PWM driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 66 of file pwm_lld.c.
References pwmObjectInit().
Referenced by pwmInit().
void pwm_lld_start (PWMDriver * pwmp)
Configures and activates the PWM peripheral.
Parameters
[in] pwmp pointer to the PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file pwm_lld.c.
References PWM_STOP, and PWMDriver::state.
Referenced by pwmStart().
void pwm_lld_stop (PWMDriver * pwmp)
Deactivates the PWM peripheral.
Parameters
[in] pwmp pointer to the PWMDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 102 of file pwm_lld.c.
References PWM_READY, and PWMDriver::state.
Referenced by pwmStop().
void pwm_lld_change_period (PWMDriver * pwmp, pwmcnt_t period)
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
The function has effect at the next cycle start.
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] period new cycle time in ticks
Function Class:
Not an API, this function is for internal use only.
Definition at line 132 of file pwm_lld.c.
void pwm_lld_enable_channel (PWMDriver * pwmp, pwmchannel_t channel, pwmcnt_t width)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
[in] width PWM pulse width as clock pulses number
Function Class:
Not an API, this function is for internal use only.
Definition at line 153 of file pwm_lld.c.
Referenced by pwmEnableChannel().
void pwm_lld_disable_channel (PWMDriver * pwmp, pwmchannel_t channel)
Disables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Function Class:
Not an API, this function is for internal use only.
Definition at line 177 of file pwm_lld.c.
Referenced by pwmDisableChannel().
Variable Documentation
PWMDriver PWMD1
PWM1 driver identifier.
Definition at line 42 of file pwm_lld.c.
Macro Definition Documentation
#define PWM_OUTPUT_MASK 0x0F
Standard output modes mask.
Definition at line 52 of file pwm.h.
#define PWM_OUTPUT_DISABLED 0x00
Output not driven, callback only.
Definition at line 57 of file pwm.h.
#define PWM_OUTPUT_ACTIVE_HIGH 0x01
Positive PWM logic, active is logic level one.
Definition at line 62 of file pwm.h.
#define PWM_OUTPUT_ACTIVE_LOW 0x02
Inverse PWM logic, active is logic level zero.
Definition at line 67 of file pwm.h.
#define PWM_FRACTION_TO_WIDTH (pwmp, denominator, numerator)
Value:
((pwmcnt_t)((((pwmcnt_t)(pwmp)->period) *                                 \
               (pwmcnt_t)(numerator)) / (pwmcnt_t)(denominator)))
Converts from fraction to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] denominator denominator of the fraction
[in] numerator numerator of the fraction
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 127 of file pwm.h.
#define PWM_DEGREES_TO_WIDTH (pwmp, degrees) PWM_FRACTION_TO_WIDTH(pwmp, 36000, degrees)
Converts from degrees to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify hundredths of degrees but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] degrees degrees as an integer between 0 and 36000
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 144 of file pwm.h.
#define PWM_PERCENTAGE_TO_WIDTH (pwmp, percentage) PWM_FRACTION_TO_WIDTH(pwmp, 10000, percentage)
Converts from percentage to pulse width.
Note
Be careful with rounding errors, this is integer math not magic. You can specify tenths of thousandth but make sure you have the proper hardware resolution by carefully choosing the clock source and prescaler settings, see PWM_COMPUTE_PSC.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] percentage percentage as an integer between 0 and 10000
Returns
The pulse width to be passed to pwmEnableChannel().
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 160 of file pwm.h.
#define pwmChangePeriodI (pwmp, value)
Value:
{                                     \
  (pwmp)->period = (value);                                                 \
  pwm_lld_change_period(pwmp, value);                                       \
}
Changes the period the PWM peripheral.
This function changes the period of a PWM unit that has already been activated using pwmStart().
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The PWM unit period is changed to the new value.
Note
If a period is specified that is shorter than the pulse width programmed in one of the channels then the behavior is not guaranteed.
Parameters
[in] pwmp pointer to a PWMDriver object
[in] value new cycle time in ticks
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 183 of file pwm.h.
Referenced by pwmChangePeriod().
#define pwmEnableChannelI (pwmp, channel, width) pwm_lld_enable_channel(pwmp, channel, width)
Enables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is active using the specified configuration.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
[in] width PWM pulse width as clock pulses number
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 202 of file pwm.h.
#define pwmDisableChannelI (pwmp, channel) pwm_lld_disable_channel(pwmp, channel)
Disables a PWM channel.
Precondition
The PWM unit must have been activated using pwmStart().
Postcondition
The channel is disabled and its output line returned to the idle state.
Note
Depending on the hardware implementation this function has effect starting on the next cycle (recommended implementation) or immediately (fallback implementation).
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 219 of file pwm.h.
#define pwmIsChannelEnabledI (pwmp, channel) pwm_lld_is_channel_enabled(pwmp, channel)
Returns a PWM channel status.
Precondition
The PWM unit must have been activated using pwmStart().
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 231 of file pwm.h.
#define PWM_CHANNELS 4
Number of PWM channels per PWM driver.
Definition at line 37 of file pwm_lld.h.
Referenced by pwmDisableChannel(), and pwmEnableChannel().
#define PLATFORM_PWM_USE_PWM1 FALSE
PWM driver enable switch.
If set to TRUE the support for PWM1 is included.
Definition at line 52 of file pwm_lld.h.
#define pwm_lld_is_channel_enabled (pwmp, channel) FALSE
Returns a PWM channel status.
Precondition
The PWM unit must have been activated using pwmStart().
Parameters
[in] pwmp pointer to a PWMDriver object
[in] channel PWM channel identifier (0...PWM_CHANNELS-1)
Function Class:
Not an API, this function is for internal use only.
Definition at line 166 of file pwm_lld.h.
Typedef Documentation
typedef struct PWMDriver PWMDriver
Type of a structure representing a PWM driver.
Definition at line 94 of file pwm.h.
typedef void(* pwmcallback_t) (PWMDriver *pwmp)
PWM notification callback type.
Parameters
[in] pwmp pointer to a PWMDriver object
Definition at line 101 of file pwm.h.
typedef uint32_t pwmmode_t
PWM mode type.
Definition at line 67 of file pwm_lld.h.
typedef uint8_t pwmchannel_t
PWM channel type.
Definition at line 72 of file pwm_lld.h.
typedef uint16_t pwmcnt_t
PWM counter type.
Definition at line 77 of file pwm_lld.h.
Enumeration Type Documentation
enum pwmstate_t
Driver state machine possible states.
Enumerator
PWM_UNINIT
Not initialized.
PWM_STOP
Stopped.
PWM_READY
Ready.
Definition at line 85 of file pwm.h.