LWIP_THREAD
LWIP_THREAD
Detailed Description
Data Structures
struct lwipthread_opts
Runtime TCP/IP settings.
Functions
WORKING_AREA (wa_lwip_thread, LWIP_THREAD_STACK_SIZE)
msg_t lwip_thread (void *p)
LWIP handling thread.
Macros
#define LWIP_THREAD_PRIORITY LOWPRIO
MAC thread priority.
#define LWIP_THREAD_STACK_SIZE 512
MAC thread stack size.
#define LWIP_LINK_POLL_INTERVAL S2ST(5)
Link poll interval.
#define LWIP_IPADDR(p) IP4_ADDR(p, 192, 168, 1, 20)
IP Address.
#define LWIP_GATEWAY(p) IP4_ADDR(p, 192, 168, 1, 1)
IP Gateway.
#define LWIP_NETMASK(p) IP4_ADDR(p, 255, 255, 255, 0)
IP netmask.
#define LWIP_SEND_TIMEOUT 50
Transmission timeout.
#define LWIP_LINK_SPEED 100000000
Link speed.
#define LWIP_ETHADDR_0 0xC2
MAC Address byte 0.
#define LWIP_ETHADDR_1 0xAF
MAC Address byte 1.
#define LWIP_ETHADDR_2 0x51
MAC Address byte 2.
#define LWIP_ETHADDR_3 0x03
MAC Address byte 3.
#define LWIP_ETHADDR_4 0xCF
MAC Address byte 4.
#define LWIP_ETHADDR_5 0x46
MAC Address byte 5.
#define LWIP_IFNAME0 'm'
Interface name byte 0.
#define LWIP_IFNAME1 's'
Interface name byte 1.
Function Documentation
WORKING_AREA (wa_lwip_thread , LWIP_THREAD_STACK_SIZE)
Stack area for the LWIP-MAC thread.
msg_t lwip_thread (void * p)
LWIP handling thread.
Parameters
[in] p pointer to a lwipthread_opts structure or NULL
Returns
The function does not return.
Definition at line 214 of file lwipthread.c.
References ALL_EVENTS, chEvtAddEvents(), chEvtRegisterMask(), chEvtWaitAny(), chRegSetThreadName, chThdSetPriority(), ETHD1, evtInit, evtStart(), LWIP_ETHADDR_0, LWIP_ETHADDR_1, LWIP_ETHADDR_2, LWIP_ETHADDR_3, LWIP_ETHADDR_4, LWIP_ETHADDR_5, LWIP_GATEWAY, LWIP_IPADDR, LWIP_LINK_POLL_INTERVAL, LWIP_NETMASK, LWIP_THREAD_PRIORITY, macGetReceiveEventSource, macPollLinkStatus(), macStart(), and TRUE.
Macro Definition Documentation
#define LWIP_THREAD_PRIORITY LOWPRIO
MAC thread priority.
Definition at line 31 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_THREAD_STACK_SIZE 512
MAC thread stack size.
Definition at line 36 of file lwipthread.h.
#define LWIP_LINK_POLL_INTERVAL S2ST(5)
Link poll interval.
Definition at line 41 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_IPADDR (p) IP4_ADDR(p, 192, 168, 1, 20)
IP Address.
Definition at line 46 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_GATEWAY (p) IP4_ADDR(p, 192, 168, 1, 1)
IP Gateway.
Definition at line 51 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_NETMASK (p) IP4_ADDR(p, 255, 255, 255, 0)
IP netmask.
Definition at line 56 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_SEND_TIMEOUT 50
Transmission timeout.
Definition at line 61 of file lwipthread.h.
#define LWIP_LINK_SPEED 100000000
Link speed.
Definition at line 66 of file lwipthread.h.
#define LWIP_ETHADDR_0 0xC2
MAC Address byte 0.
Definition at line 71 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_ETHADDR_1 0xAF
MAC Address byte 1.
Definition at line 76 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_ETHADDR_2 0x51
MAC Address byte 2.
Definition at line 81 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_ETHADDR_3 0x03
MAC Address byte 3.
Definition at line 86 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_ETHADDR_4 0xCF
MAC Address byte 4.
Definition at line 91 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_ETHADDR_5 0x46
MAC Address byte 5.
Definition at line 96 of file lwipthread.h.
Referenced by lwip_thread().
#define LWIP_IFNAME0 'm'
Interface name byte 0.
Definition at line 101 of file lwipthread.h.
#define LWIP_IFNAME1 's'
Interface name byte 1.
Definition at line 106 of file lwipthread.h.