ICU Driver
ICU Driver
HAL
Detailed Description
Generic ICU Driver.
This module implements a generic ICU (Input Capture Unit) driver.
Precondition
In order to use the ICU driver the HAL_USE_ICU option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
ICU Operations.
This driver abstracts a generic Input Capture Unit composed of:
A clock prescaler.
A main up counter.
Two capture registers triggered by the rising and falling edges on the sampled input.
The ICU unit can be programmed to synchronize on the rising or falling edge of the sample input:
ICU_INPUT_ACTIVE_HIGH, a rising edge is the start signal.
ICU_INPUT_ACTIVE_LOW, a falling edge is the start signal.
After the activation the ICU unit can be in one of the following states at any time:
ICU_WAITING, waiting the first start signal.
ICU_ACTIVE, after a start signal.
ICU_IDLE, after a stop signal.
Callbacks are invoked when start or stop signals occur.
Data Structures
struct ICUConfig
Driver configuration structure.
struct ICUDriver
Structure representing an ICU driver.
Functions
void icuInit (void)
ICU Driver initialization.
void icuObjectInit (ICUDriver *icup)
Initializes the standard part of a ICUDriver structure.
void icuStart (ICUDriver *icup, const ICUConfig *config)
Configures and activates the ICU peripheral.
void icuStop (ICUDriver *icup)
Deactivates the ICU peripheral.
void icuEnable (ICUDriver *icup)
Enables the input capture.
void icuDisable (ICUDriver *icup)
Disables the input capture.
void icu_lld_init (void)
Low level ICU driver initialization.
void icu_lld_start (ICUDriver *icup)
Configures and activates the ICU peripheral.
void icu_lld_stop (ICUDriver *icup)
Deactivates the ICU peripheral.
void icu_lld_enable (ICUDriver *icup)
Enables the input capture.
void icu_lld_disable (ICUDriver *icup)
Disables the input capture.
icucnt_t icu_lld_get_width (ICUDriver *icup)
Returns the width of the latest pulse.
icucnt_t icu_lld_get_period (ICUDriver *icup)
Returns the width of the latest cycle.
Variables
ICUDriver ICUD1
ICU1 driver identifier.
Macro Functions
#define icuEnableI(icup) icu_lld_enable(icup)
Enables the input capture.
#define icuDisableI(icup) icu_lld_disable(icup)
Disables the input capture.
#define icuGetWidth(icup) icu_lld_get_width(icup)
Returns the width of the latest pulse.
#define icuGetPeriod(icup) icu_lld_get_period(icup)
Returns the width of the latest cycle.
Low Level driver helper macros
#define _icu_isr_invoke_width_cb(icup)
Common ISR code, ICU width event.
#define _icu_isr_invoke_period_cb(icup)
Common ISR code, ICU period event.
#define _icu_isr_invoke_overflow_cb(icup)
Common ISR code, ICU timer overflow event.
Configuration options
#define PLATFORM_ICU_USE_ICU1 FALSE
ICU driver enable switch.
Typedefs
typedef struct ICUDriver ICUDriver
Type of a structure representing an ICU driver.
typedef void(* icucallback_t) (ICUDriver *icup)
ICU notification callback type.
typedef uint32_t icufreq_t
ICU frequency type.
typedef uint16_t icucnt_t
ICU counter type.
Enumerations
enum icustate_t {
ICU_UNINIT = 0, ICU_STOP = 1, ICU_READY = 2, ICU_WAITING = 3,
ICU_ACTIVE = 4, ICU_IDLE = 5
}
Driver state machine possible states.
enum icumode_t { ICU_INPUT_ACTIVE_HIGH = 0, ICU_INPUT_ACTIVE_LOW = 1 }
ICU driver mode.
Function Documentation
void icuInit (void)
ICU Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file icu.c.
References icu_lld_init().
Referenced by halInit().
void icuObjectInit (ICUDriver * icup)
Initializes the standard part of a ICUDriver structure.
Parameters
[out] icup pointer to the ICUDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 80 of file icu.c.
References ICUDriver::config, ICU_STOP, and ICUDriver::state.
Referenced by icu_lld_init().
void icuStart (ICUDriver * icup, const ICUConfig * config)
Configures and activates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
[in] config pointer to the ICUConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 94 of file icu.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, ICUDriver::config, icu_lld_start(), ICU_READY, ICU_STOP, and ICUDriver::state.
void icuStop (ICUDriver * icup)
Deactivates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 114 of file icu.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, icu_lld_stop(), ICU_READY, ICU_STOP, and ICUDriver::state.
void icuEnable (ICUDriver * icup)
Enables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 133 of file icu.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, icu_lld_enable(), ICU_READY, ICU_WAITING, and ICUDriver::state.
void icuDisable (ICUDriver * icup)
Disables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 151 of file icu.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, ICU_ACTIVE, ICU_IDLE, icu_lld_disable(), ICU_READY, ICU_WAITING, and ICUDriver::state.
void icu_lld_init (void)
Low level ICU driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 66 of file icu_lld.c.
References icuObjectInit().
Referenced by icuInit().
void icu_lld_start (ICUDriver * icup)
Configures and activates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file icu_lld.c.
References ICU_STOP, and ICUDriver::state.
Referenced by icuStart().
void icu_lld_stop (ICUDriver * icup)
Deactivates the ICU peripheral.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 102 of file icu_lld.c.
References ICU_READY, and ICUDriver::state.
Referenced by icuStop().
void icu_lld_enable (ICUDriver * icup)
Enables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 123 of file icu_lld.c.
Referenced by icuEnable().
void icu_lld_disable (ICUDriver * icup)
Disables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 136 of file icu_lld.c.
Referenced by icuDisable().
icucnt_t icu_lld_get_width (ICUDriver * icup)
Returns the width of the latest pulse.
The pulse width is defined as number of ticks between the start edge and the stop edge.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Not an API, this function is for internal use only.
Definition at line 152 of file icu_lld.c.
icucnt_t icu_lld_get_period (ICUDriver * icup)
Returns the width of the latest cycle.
The cycle width is defined as number of ticks between a start edge and the next start edge.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Not an API, this function is for internal use only.
Definition at line 169 of file icu_lld.c.
Variable Documentation
ICUDriver ICUD1
ICU1 driver identifier.
Definition at line 42 of file icu_lld.c.
Macro Definition Documentation
#define icuEnableI (icup) icu_lld_enable(icup)
Enables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 98 of file icu.h.
#define icuDisableI (icup) icu_lld_disable(icup)
Disables the input capture.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 107 of file icu.h.
#define icuGetWidth (icup) icu_lld_get_width(icup)
Returns the width of the latest pulse.
The pulse width is defined as number of ticks between the start edge and the stop edge.
Note
This function is meant to be invoked from the width capture callback only.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 121 of file icu.h.
#define icuGetPeriod (icup) icu_lld_get_period(icup)
Returns the width of the latest cycle.
The cycle width is defined as number of ticks between a start edge and the next start edge.
Note
This function is meant to be invoked from the width capture callback only.
Parameters
[in] icup pointer to the ICUDriver object
Returns
The number of ticks.
Function Class:
Special function, this function has special requirements see the notes.
Definition at line 135 of file icu.h.
#define _icu_isr_invoke_width_cb (icup)
Value:
{                                    \
  if ((icup)->state != ICU_WAITING) {                                       \
    (icup)->state = ICU_IDLE;                                               \
    (icup)->config->width_cb(icup);                                         \
  }                                                                         \
}
Common ISR code, ICU width event.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 149 of file icu.h.
#define _icu_isr_invoke_period_cb (icup)
Value:
{                                   \
  icustate_t previous_state = (icup)->state;                                \
  (icup)->state = ICU_ACTIVE;                                               \
  if (previous_state != ICU_WAITING)                                        \
    (icup)->config->period_cb(icup);                                        \
}
Common ISR code, ICU period event.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 163 of file icu.h.
#define _icu_isr_invoke_overflow_cb (icup)
Value:
{                                 \
  (icup)->config->overflow_cb(icup);                                        \
}
Common ISR code, ICU timer overflow event.
Parameters
[in] icup pointer to the ICUDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 177 of file icu.h.
#define PLATFORM_ICU_USE_ICU1 FALSE
ICU driver enable switch.
If set to TRUE the support for ICU1 is included.
Definition at line 51 of file icu_lld.h.
Typedef Documentation
typedef struct ICUDriver ICUDriver
Type of a structure representing an ICU driver.
Definition at line 72 of file icu.h.
typedef void(* icucallback_t) (ICUDriver *icup)
ICU notification callback type.
Parameters
[in] icup pointer to a ICUDriver object
Definition at line 79 of file icu.h.
typedef uint32_t icufreq_t
ICU frequency type.
Definition at line 74 of file icu_lld.h.
typedef uint16_t icucnt_t
ICU counter type.
Definition at line 79 of file icu_lld.h.
Enumeration Type Documentation
enum icustate_t
Driver state machine possible states.
Enumerator
ICU_UNINIT
Not initialized.
ICU_STOP
Stopped.
ICU_READY
Ready.
ICU_WAITING
Waiting first edge.
ICU_ACTIVE
Active cycle phase.
ICU_IDLE
Idle cycle phase.
Definition at line 60 of file icu.h.
enum icumode_t
ICU driver mode.
Enumerator
ICU_INPUT_ACTIVE_HIGH
Trigger on rising edge.
ICU_INPUT_ACTIVE_LOW
Trigger on falling edge.
Definition at line 66 of file icu_lld.h.