UART Driver
UART Driver
HAL
Detailed Description
Generic UART Driver.
This driver abstracts a generic UART (Universal Asynchronous Receiver Transmitter) peripheral, the API is designed to be:
Unbuffered and copy-less, transfers are always directly performed from/to the application-level buffers without extra copy operations.
Asynchronous, the API is always non blocking.
Callbacks capable, operations completion and other events are notified using callbacks.
Special hardware features like deep hardware buffers, DMA transfers are hidden to the user but fully supportable by the low level implementations.
This driver model is best used where communication events are meant to drive an higher level state machine, as example:
RS485 drivers.
Multipoint network drivers.
Serial protocol decoders.
If your application requires a synchronous buffered driver then the Serial Driver should be used instead.
Precondition
In order to use the UART driver the HAL_USE_UART option must be enabled in halconf.h.
Driver State Machine
The driver implements a state machine internally, not all the driver functionalities can be used in any moment, any transition not explicitly shown in the following diagram has to be considered an error and shall be captured by an assertion (if enabled).
Transmitter sub State Machine
The follow diagram describes the transmitter state machine, this diagram is valid while the driver is in the UART_READY state. This state machine is automatically reset to the TX_IDLE state each time the driver enters the UART_READY state.
Receiver sub State Machine
The follow diagram describes the receiver state machine, this diagram is valid while the driver is in the UART_READY state. This state machine is automatically reset to the RX_IDLE state each time the driver enters the UART_READY state.
Data Structures
struct UARTConfig
Driver configuration structure.
struct UARTDriver
Structure representing an UART driver.
Functions
void uartInit (void)
UART Driver initialization.
void uartObjectInit (UARTDriver *uartp)
Initializes the standard part of a UARTDriver structure.
void uartStart (UARTDriver *uartp, const UARTConfig *config)
Configures and activates the UART peripheral.
void uartStop (UARTDriver *uartp)
Deactivates the UART peripheral.
void uartStartSend (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
void uartStartSendI (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
size_t uartStopSend (UARTDriver *uartp)
Stops any ongoing transmission.
size_t uartStopSendI (UARTDriver *uartp)
Stops any ongoing transmission.
void uartStartReceive (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
void uartStartReceiveI (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
size_t uartStopReceive (UARTDriver *uartp)
Stops any ongoing receive operation.
size_t uartStopReceiveI (UARTDriver *uartp)
Stops any ongoing receive operation.
void uart_lld_init (void)
Low level UART driver initialization.
void uart_lld_start (UARTDriver *uartp)
Configures and activates the UART peripheral.
void uart_lld_stop (UARTDriver *uartp)
Deactivates the UART peripheral.
void uart_lld_start_send (UARTDriver *uartp, size_t n, const void *txbuf)
Starts a transmission on the UART peripheral.
size_t uart_lld_stop_send (UARTDriver *uartp)
Stops any ongoing transmission.
void uart_lld_start_receive (UARTDriver *uartp, size_t n, void *rxbuf)
Starts a receive operation on the UART peripheral.
size_t uart_lld_stop_receive (UARTDriver *uartp)
Stops any ongoing receive operation.
Variables
UARTDriver UARTD1
UART1 driver identifier.
UART status flags
#define UART_NO_ERROR 0
No pending conditions.
#define UART_PARITY_ERROR 4
Parity error happened.
#define UART_FRAMING_ERROR 8
Framing error happened.
#define UART_OVERRUN_ERROR 16
Overflow happened.
#define UART_NOISE_ERROR 32
Noise on the line.
#define UART_BREAK_DETECTED 64
Break detected.
Configuration options
#define PLATFORM_UART_USE_UART1 FALSE
UART driver enable switch.
Typedefs
typedef uint32_t uartflags_t
UART driver condition flags type.
typedef struct UARTDriver UARTDriver
Type of structure representing an UART driver.
typedef void(* uartcb_t) (UARTDriver *uartp)
Generic UART notification callback type.
typedef void(* uartccb_t) (UARTDriver *uartp, uint16_t c)
Character received UART notification callback type.
typedef void(* uartecb_t) (UARTDriver *uartp, uartflags_t e)
Receive error UART notification callback type.
Enumerations
enum uartstate_t { UART_UNINIT = 0, UART_STOP = 1, UART_READY = 2 }
Driver state machine possible states.
enum uarttxstate_t { UART_TX_IDLE = 0, UART_TX_ACTIVE = 1, UART_TX_COMPLETE = 2 }
Transmitter state machine states.
enum uartrxstate_t { UART_RX_IDLE = 0, UART_RX_ACTIVE = 1, UART_RX_COMPLETE = 2 }
Receiver state machine states.
Function Documentation
void uartInit (void)
UART Driver initialization.
Note
This function is implicitly invoked by halInit(), there is no need to explicitly initialize the driver.
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 68 of file uart.c.
References uart_lld_init().
Referenced by halInit().
void uartObjectInit (UARTDriver * uartp)
Initializes the standard part of a UARTDriver structure.
Parameters
[out] uartp pointer to the UARTDriver object
Function Class:
Initializer, this function just initializes an object and can be invoked before the kernel is initialized.
Definition at line 80 of file uart.c.
References UARTDriver::config, UARTDriver::rxstate, UARTDriver::state, UARTDriver::txstate, UART_RX_IDLE, UART_STOP, and UART_TX_IDLE.
Referenced by uart_lld_init().
void uartStart (UARTDriver * uartp, const UARTConfig * config)
Configures and activates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
[in] config pointer to the UARTConfig object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 100 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::config, UARTDriver::state, uart_lld_start(), UART_READY, and UART_STOP.
void uartStop (UARTDriver * uartp)
Deactivates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 121 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::rxstate, UARTDriver::state, UARTDriver::txstate, uart_lld_stop(), UART_READY, UART_RX_IDLE, UART_STOP, and UART_TX_IDLE.
void uartStartSend (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 147 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::state, UARTDriver::txstate, uart_lld_start_send(), UART_READY, and UART_TX_ACTIVE.
void uartStartSendI (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 175 of file uart.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), UARTDriver::state, UARTDriver::txstate, uart_lld_start_send(), UART_READY, and UART_TX_ACTIVE.
size_t uartStopSend (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Return values
0 There was no transmit operation in progress.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 201 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::state, UARTDriver::txstate, uart_lld_stop_send(), UART_READY, UART_TX_ACTIVE, and UART_TX_IDLE.
size_t uartStopSendI (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Return values
0 There was no transmit operation in progress.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 232 of file uart.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), UARTDriver::state, UARTDriver::txstate, uart_lld_stop_send(), UART_READY, UART_TX_ACTIVE, and UART_TX_IDLE.
void uartStartReceive (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] rxbuf the pointer to the receive buffer
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 257 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::rxstate, UARTDriver::state, uart_lld_start_receive(), UART_READY, and UART_RX_ACTIVE.
void uartStartReceiveI (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[out] rxbuf the pointer to the receive buffer
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 285 of file uart.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), UARTDriver::rxstate, UARTDriver::state, uart_lld_start_receive(), UART_READY, and UART_RX_ACTIVE.
size_t uartStopReceive (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Return values
0 There was no receive operation in progress.
Function Class:
Normal API, this function can be invoked by regular system threads but not from within a lock zone.
Definition at line 311 of file uart.c.
References chDbgAssert, chDbgCheck, chSysLock, chSysUnlock, UARTDriver::rxstate, UARTDriver::state, uart_lld_stop_receive(), UART_READY, UART_RX_ACTIVE, and UART_RX_IDLE.
size_t uartStopReceiveI (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
This function has to be invoked from a lock zone.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Return values
0 There was no receive operation in progress.
Function Class:
This is an I-Class API, this function can be invoked from within a system lock zone by both threads and interrupt handlers.
Definition at line 343 of file uart.c.
References chDbgAssert, chDbgCheck, chDbgCheckClassI(), UARTDriver::rxstate, UARTDriver::state, uart_lld_stop_receive(), UART_READY, UART_RX_ACTIVE, and UART_RX_IDLE.
void uart_lld_init (void)
Low level UART driver initialization.
Function Class:
Not an API, this function is for internal use only.
Definition at line 66 of file uart_lld.c.
References uartObjectInit().
Referenced by uartInit().
void uart_lld_start (UARTDriver * uartp)
Configures and activates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 81 of file uart_lld.c.
References UARTDriver::state, and UART_STOP.
Referenced by uartStart().
void uart_lld_stop (UARTDriver * uartp)
Deactivates the UART peripheral.
Parameters
[in] uartp pointer to the UARTDriver object
Function Class:
Not an API, this function is for internal use only.
Definition at line 102 of file uart_lld.c.
References UARTDriver::state, and UART_READY.
Referenced by uartStop().
void uart_lld_start_send (UARTDriver * uartp, size_t n, const void * txbuf)
Starts a transmission on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[in] txbuf the pointer to the transmit buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 127 of file uart_lld.c.
Referenced by uartStartSend(), and uartStartSendI().
size_t uart_lld_stop_send (UARTDriver * uartp)
Stops any ongoing transmission.
Note
Stopping a transmission also suppresses the transmission callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not transmitted by the stopped transmit operation.
Function Class:
Not an API, this function is for internal use only.
Definition at line 146 of file uart_lld.c.
Referenced by uartStopSend(), and uartStopSendI().
void uart_lld_start_receive (UARTDriver * uartp, size_t n, void * rxbuf)
Starts a receive operation on the UART peripheral.
Note
The buffers are organized as uint8_t arrays for data sizes below or equal to 8 bits else it is organized as uint16_t arrays.
Parameters
[in] uartp pointer to the UARTDriver object
[in] n number of data frames to send
[out] rxbuf the pointer to the receive buffer
Function Class:
Not an API, this function is for internal use only.
Definition at line 164 of file uart_lld.c.
Referenced by uartStartReceive(), and uartStartReceiveI().
size_t uart_lld_stop_receive (UARTDriver * uartp)
Stops any ongoing receive operation.
Note
Stopping a receive operation also suppresses the receive callbacks.
Parameters
[in] uartp pointer to the UARTDriver object
Returns
The number of data frames not received by the stopped receive operation.
Function Class:
Not an API, this function is for internal use only.
Definition at line 183 of file uart_lld.c.
Referenced by uartStopReceive(), and uartStopReceiveI().
Variable Documentation
UARTDriver UARTD1
UART1 driver identifier.
Definition at line 42 of file uart_lld.c.
Macro Definition Documentation
#define UART_NO_ERROR 0
No pending conditions.
Definition at line 49 of file uart.h.
#define UART_PARITY_ERROR 4
Parity error happened.
Definition at line 50 of file uart.h.
#define UART_FRAMING_ERROR 8
Framing error happened.
Definition at line 51 of file uart.h.
#define UART_OVERRUN_ERROR 16
Overflow happened.
Definition at line 52 of file uart.h.
#define UART_NOISE_ERROR 32
Noise on the line.
Definition at line 53 of file uart.h.
#define UART_BREAK_DETECTED 64
Break detected.
Definition at line 54 of file uart.h.
#define PLATFORM_UART_USE_UART1 FALSE
UART driver enable switch.
If set to TRUE the support for UART1 is included.
Definition at line 47 of file uart_lld.h.
Typedef Documentation
typedef uint32_t uartflags_t
UART driver condition flags type.
Definition at line 62 of file uart_lld.h.
typedef struct UARTDriver UARTDriver
Type of structure representing an UART driver.
Definition at line 67 of file uart_lld.h.
typedef void(* uartcb_t) (UARTDriver *uartp)
Generic UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object
Definition at line 74 of file uart_lld.h.
typedef void(* uartccb_t) (UARTDriver *uartp, uint16_t c)
Character received UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object triggering the callback
[in] c received character
Definition at line 83 of file uart_lld.h.
typedef void(* uartecb_t) (UARTDriver *uartp, uartflags_t e)
Receive error UART notification callback type.
Parameters
[in] uartp pointer to the UARTDriver object triggering the callback
[in] e receive error mask
Definition at line 92 of file uart_lld.h.
Enumeration Type Documentation
enum uartstate_t
Driver state machine possible states.
Enumerator
UART_UNINIT
Not initialized.
UART_STOP
Stopped.
UART_READY
Ready.
Definition at line 72 of file uart.h.
enum uarttxstate_t
Transmitter state machine states.
Enumerator
UART_TX_IDLE
Not transmitting.
UART_TX_ACTIVE
Transmitting.
UART_TX_COMPLETE
Buffer complete.
Definition at line 81 of file uart.h.
enum uartrxstate_t
Receiver state machine states.
Enumerator
UART_RX_IDLE
Not receiving.
UART_RX_ACTIVE
Receiving.
UART_RX_COMPLETE
Buffer complete.
Definition at line 90 of file uart.h.